# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install CocoaPods dependencies
      run: pod install
      working-directory: ./Users/nate/Documents/code/personal/TagalogConjugation-iOS/Tagalog Conjugation/Tagalog Conjugation.xcworkspace
    - name: Build
      run: swift build
      working-directory: ./Users/nate/Documents/code/personal/TagalogConjugation-iOS/Tagalog Conjugation/Tagalog Conjugation.xcworkspace
    - name: Run tests
      run: swift test
      working-directory: ./Users/nate/Documents/code/personal/TagalogConjugation-iOS/Tagalog Conjugation/Tagalog Conjugation.xcworkspace
